version: '3.2'
services:
  live_view_studio_2ed_dev:
    image: postgres:latest
    expose:
      - '5433'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB:
        live_view_studio_2ed_dev
        
